### ISSUE TITLE
Failed to activate the local-storage package

### ISSUE THREAD

**Issue by onaforeignshore** [idleberg/atom-local-storage#2]
[Enter steps to reproduce:]

1. Update extensions

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [local-storage](https://github.com/idleberg/atom-local-storage) package 0.12.1

### Stack Trace

Failed to activate the local-storage package

```
At The "path" argument must be of type string. Received type undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:1155:7)
    at PackageManager.resolvePackagePath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:374759)
    at /packages/local-storage/lib/main.js:1:17038)
    at Object.t.readManifestSync (/packages/local-storage/lib/main.js:1:17456)
    at /packages/local-storage/lib/main.js:1:13847)
    at /packages/local-storage/lib/main.js:1:279)
    at /packages/local-storage/lib/main.js:1:2599)
    at /packages/local-storage/lib/main.js:1:279)
    at /packages/local-storage/lib/main.js:1:13142)
    at /packages/local-storage/lib/main.js:1:279)
    at /packages/local-storage/lib/main.js:1:1078
    at /packages/local-storage/lib/main.js:1:1088)
    at /packages/local-storage/lib/main.js:3:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:694511)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3226484)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3214468)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1214427)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382896)
    at activatePromise.Promise.all.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381647)
```

### Commands

```
     -0:06.0 core:copy (a.)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-reverser 3.0.4 
auto-detect-indentation 1.3.0 
auto-reveal-in-sidebar 0.8.0 
autocomplete-gas 0.11.1 
browse 2.6.2 
browser-plus 0.0.98 
busy-signal 2.0.1 
city-lights-icons 1.1.1 
color-picker 2.3.0 
compare-files 0.8.1 
cursor-history 0.14.0 
cursor-indicator 1.3.0 
custom-title 1.0.1 
expose 0.15.0 
git-plus 8.7.1 
highlight-line 0.12.0 
highlight-nanorc 0.9.0 
highlight-selected 0.17.0 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-applescript 0.3.0 
language-awk 0.1.12 
language-ini 1.23.0 
language-markdown 0.37.0 
language-todotxt-plus 1.6.1 
language-unix-shell 0.40.1 
language-viml 1.2.0 
language-xst 0.5.0 
local-storage 0.12.1 
markdown-folding 0.3.1 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.1.2 
markdown-writer 2.11.10 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
multi-cursor-plus 1.2.0 
omni-ruler 0.6.0 
open-in-developer-mode 0.3.0 
open-package 0.2.0 
open-recent 5.0.0 
package-sync 1.1.0 
pigments 0.40.2 
platformio-ide-terminal 2.10.0 
print-atom 0.1.1 
print-code 0.7.1 
project-manager 3.3.8 
react 0.18.0 
rename-tabs 0.2.0 
satisfy-dependencies 0.4.2 
scroll-marker 0.3.2 
seti-icons 1.5.4 
seti-syntax 1.2.0 
seti-ui 1.11.0 
show-invisibles-plus 0.3.1 
simple-drag-drop-text 0.5.0 
sort-lines 0.19.0 
sorter 1.3.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.5 
tabs-to-spaces 1.0.5 
todo-show 2.3.2 
tool-bar 1.2.2 
tool-bar-markdown-writer 0.5.1 
vim-modeline 0.5.2 
wordcount 3.1.0 
```

**Comment by idleberg** [comment]
How was the package installed?

**Comment by onaforeignshore** [comment]
Inside atom using Cmd+, and Install

**Comment by idleberg** [comment]
Technically, the error is not thrown by `local-storage` but one of its dependencies ([atom-read-manifest](https://www.npmjs.org/package/atom-read-manifest)). I will see what I can do, but of course it would help if I was able to reproduce the error – so it might take a while.

Have you tried the obvious, like re-installing the package? Did the error occur on launch or after running one of its commands? In normal mode or developer mode?

**Comment by onaforeignshore** [comment]
I have reinstalled it but still got the same error. The error occurs on opening Atom. I am using normal mode.

**Comment by idleberg** [comment]
I've tested this on two Windows machines, macOS and Fedora, but unfortunately I cannot reproduce the problem. The most recent has updated dependencies, if that changes anything for you. Otherwise,  I'm afraid there's not much else I can do 😔
